version: '3.3'
services:

  app:
    ports:
      - "80:8000"
    depends_on:
      - postgres
      - elasticsearch
    build: ./app
    volumes:
      - ./app/:/app/
    command:
      python ./manage.py runserver 0.0.0.0:8000
    environment:
      - INIT_DEMO=True
    
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    image: launcher.gcr.io/google/elasticsearch2
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
  esdata:
  pgdata:
